easage-pack: Make kind optional with BIGF as default
Phrohdoh/easage pull request #35
Opened 2018-01-26 22:42 UTC by Teteros

2018-01-26 22:43 UTC, phrohdoh requested changes
Please create constants and use those in `default_value` and `possible_values`.

2018-01-26 23:49 UTC, Teteros commented
@Phrohdoh Done.

2018-01-27 19:19 UTC, phrohdoh requested changes

2018-01-27 19:19 UTC, Phrohdoh commented on src/bin/easage_pack.rs
> +                .help("FourCC to use (case-sensitive)"))
Please change this to `use BIG4 for the Battle for Middle-Earth series or BIGF for Generals / Zero-Hour` (intentionally not including the `(case-sensitive)` bit which I have changed my mind about).

LGTM after that.

2018-01-27 19:27 UTC, phrohdoh approved these changes

2018-01-27 19:30 UTC, merged